### PR TITLE
Feature Fixes and Updates

### PR DESCRIPTION
**Pull request by xViperAG**

### CODE REVIEW

**Comment by xFutte** [comment]
@xViperAG Pretty good idea. However, the current code doesn't, after testing it locally, not get rid of the newspaper prop from the body when closing the newspaper.

**Comment by xViperAG** [comment]
So it had worked perfectly for me and I did it numerous times to make sure of it.

Since it's a client side thing might require a cache clear on either user side or server side just to make sure

**Comment by xFutte** [comment]
> So it had worked perfectly for me and I did it numerous times to make sure of it.
> 
> Since it's a client side thing might require a cache clear on either user side or server side just to make sure

Good point. I'll give it a go and see.

**Review by xFutte — APPROVED** [review]
It works as intended after clearing the cache. Will be merged master. Thanks.

**Pull request merged**
